### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by ZilinIB** [CompVis/content-style-disentangled-ST#2]
Hi! I'm a student from ETH Zurich. Your work is really amazing! I'd appreciate it if I can get to know more implementation detail. May I ask when you will release the source code?

**Comment by dimakot55** [comment]
Hey @ZilinIB the working version of the code has just been uploaded. Feel free to apply it to your data. I'm refactoring the code right now - adding comments and changing variables names to make naming more consistent with the paper itself. 
So code will be updated.

**Comment by asanakoy** [comment]
Preliminary version of the source code is located in this branch https://github.com/CompVis/content-style-disentangled-ST/tree/dev_subm_1

**Comment by ZilinIB** [comment]
Thank you guys a lot!
