### ISSUE TITLE
Difference in content loss function

### ISSUE THREAD

**Issue by hwidong-na** [CompVis/content-style-disentangled-ST#3]
Hi,

Thank you for releasing your great work.

I found a difference b/w the code and the paper description for the content loss.

code: https://github.com/CompVis/content-style-disentangled-ST/blob/dev_subm_1/model.py#L288

In the paper, it is the mean squared error.

Any reasons for this differences?

**Comment by asanakoy** [comment]
Hi,

Thanks for noticing that!
Cosine distance is the same as euclidean distance (up to a constant factor) if the vectors have a unit norm. So in our case these losses are equavalent.

![image](https://user-images.githubusercontent.com/1690869/79476068-d4698400-8008-11ea-8c79-54fdc16396e7.png)
